package com.smarthost.challenge;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * This class was auto-generated by the Spring Boot initializer and starts the application.
 * @author Rene Castillo
 */
@SpringBootApplication
public class SmarthostApplication {

	public static void main(String[] args) {
		SpringApplication.run(SmarthostApplication.class, args);
	}
}